### ISSUE TITLE
padding is not work well 

### ISSUE THREAD

**Issue by appbeijing** [sahlhoff/rn-bootstrap-buttons#1]
texts: {
    margin:10,
    fontSize: 16,
    color: '#fff',
    fontWeight: '400'
  },
padding is not work on my phone ,I use the tag of margin, it works well, I can't understander why you hide your styles

**Comment by sahlhoff** [comment]
Hi @appbeijing,

If you want to add custom styles you will have to add them to the buttonStyle or textStyle property. Please look at the readme custom button example for more detail.
